### ISSUE TITLE
bug: reddit link don't point to reddit

### ISSUE THREAD

**Issue by hugosenari** [Yardanico/nimeventer#1]
**Actual Behavior**:
Reddit post direct to link URL

_Example_:
> New post on r/nim by PMunch: Optimising for Humans - Nim presentation at FOSDEM '21, see https://fosdem.org/2021/schedule/event/nimdsl/

**Expected Behavior**:
Reddit post direct to reddit post URL

_Example_:
> New post on r/nim by PMunch: Optimising for Humans - Nim presentation at FOSDEM '21, see https://www.reddit.com/r/nim/comments/lenlf3/optimising_for_humans_nim_presentation_at_fosdem/

**Additional Info:**
When reddit post where sent it could be in two types:

1 - Text where `url` point to itself
![image](https://user-images.githubusercontent.com/863299/107549713-eb3c2100-6bae-11eb-8b5d-3bb94f76bad7.png)

2 - Link where `url` point to link URL
![image](https://user-images.githubusercontent.com/863299/107549005-15411380-6bae-11eb-944a-270a2525a086.png)

https://www.reddit.com/r/nim/new.json

**Comment by Yardanico** [comment]
Thanks, will fix soon
